version: '3'

services:
  app:
    build: ./
    image: stasmo/weatherlinkscanner
    command: npm start
    environment:
      WEATHERLINK_API_KEY: $WEATHERLINK_API_KEY
      WEATHERLINK_API_SECRET: $WEATHERLINK_API_SECRET
      SHEET_NAME: $SHEET_NAME
    restart: always
    volumes:
      - "$FILE_DIRECTORY:/files"