version: '3'

services:
  app:
    build: ./
    image: stasmo/weatherlinkscanner
    command: npm start
    environment:
      WEATHERLINK_API_KEY: $WEATHERLINK_API_KEY
      WEATHERLINK_API_SECRET: $WEATHERLINK_API_SECRET
    restart: always
    volumes:
      - "/files:$FILE_DIRECTORY"